//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.KMS.solution.ControlTemplates.Envision.KMS.Solution.Manual {
    
    
    public partial class ManualContentCtrl {
    }
}
