//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMSServiceTest.KMSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResult", Namespace="http://schemas.datacontract.org/2004/07/KMS_Copy.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KMSServiceTest.KMSService.PagingEntity))]
    public partial class JsonResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingEntity", Namespace="http://schemas.datacontract.org/2004/07/KMS_Copy.Model.Models.Announcement")]
    [System.SerializableAttribute()]
    public partial class PagingEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LimitRowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TakeCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WikiIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string listnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weburlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdField, value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimitRows {
            get {
                return this.LimitRowsField;
            }
            set {
                if ((this.LimitRowsField.Equals(value) != true)) {
                    this.LimitRowsField = value;
                    this.RaisePropertyChanged("LimitRows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Search {
            get {
                return this.SearchField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchField, value) != true)) {
                    this.SearchField = value;
                    this.RaisePropertyChanged("Search");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TakeCount {
            get {
                return this.TakeCountField;
            }
            set {
                if ((this.TakeCountField.Equals(value) != true)) {
                    this.TakeCountField = value;
                    this.RaisePropertyChanged("TakeCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WikiId {
            get {
                return this.WikiIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WikiIdField, value) != true)) {
                    this.WikiIdField = value;
                    this.RaisePropertyChanged("WikiId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string listname {
            get {
                return this.listnameField;
            }
            set {
                if ((object.ReferenceEquals(this.listnameField, value) != true)) {
                    this.listnameField = value;
                    this.RaisePropertyChanged("listname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weburl {
            get {
                return this.weburlField;
            }
            set {
                if ((object.ReferenceEquals(this.weburlField, value) != true)) {
                    this.weburlField = value;
                    this.RaisePropertyChanged("weburl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KMSService.IGlobalService")]
    public interface IGlobalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGlobalService/GetSearchUrl", ReplyAction="http://tempuri.org/IGlobalService/GetSearchUrlResponse")]
        KMSServiceTest.KMSService.JsonResult GetSearchUrl();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGlobalService/GetSearchUrl", ReplyAction="http://tempuri.org/IGlobalService/GetSearchUrlResponse")]
        System.Threading.Tasks.Task<KMSServiceTest.KMSService.JsonResult> GetSearchUrlAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGlobalService/GetGlobalNavigation", ReplyAction="http://tempuri.org/IGlobalService/GetGlobalNavigationResponse")]
        KMSServiceTest.KMSService.JsonResult GetGlobalNavigation(KMSServiceTest.KMSService.PagingEntity obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGlobalService/GetGlobalNavigation", ReplyAction="http://tempuri.org/IGlobalService/GetGlobalNavigationResponse")]
        System.Threading.Tasks.Task<KMSServiceTest.KMSService.JsonResult> GetGlobalNavigationAsync(KMSServiceTest.KMSService.PagingEntity obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGlobalService/GetAnnouncementsItems", ReplyAction="http://tempuri.org/IGlobalService/GetAnnouncementsItemsResponse")]
        KMSServiceTest.KMSService.JsonResult GetAnnouncementsItems(KMSServiceTest.KMSService.PagingEntity obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGlobalService/GetAnnouncementsItems", ReplyAction="http://tempuri.org/IGlobalService/GetAnnouncementsItemsResponse")]
        System.Threading.Tasks.Task<KMSServiceTest.KMSService.JsonResult> GetAnnouncementsItemsAsync(KMSServiceTest.KMSService.PagingEntity obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGlobalService/GetSiteNavigation", ReplyAction="http://tempuri.org/IGlobalService/GetSiteNavigationResponse")]
        KMSServiceTest.KMSService.JsonResult GetSiteNavigation(KMSServiceTest.KMSService.PagingEntity obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGlobalService/GetSiteNavigation", ReplyAction="http://tempuri.org/IGlobalService/GetSiteNavigationResponse")]
        System.Threading.Tasks.Task<KMSServiceTest.KMSService.JsonResult> GetSiteNavigationAsync(KMSServiceTest.KMSService.PagingEntity obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGlobalServiceChannel : KMSServiceTest.KMSService.IGlobalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlobalServiceClient : System.ServiceModel.ClientBase<KMSServiceTest.KMSService.IGlobalService>, KMSServiceTest.KMSService.IGlobalService {
        
        public GlobalServiceClient() {
        }
        
        public GlobalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GlobalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KMSServiceTest.KMSService.JsonResult GetSearchUrl() {
            return base.Channel.GetSearchUrl();
        }
        
        public System.Threading.Tasks.Task<KMSServiceTest.KMSService.JsonResult> GetSearchUrlAsync() {
            return base.Channel.GetSearchUrlAsync();
        }
        
        public KMSServiceTest.KMSService.JsonResult GetGlobalNavigation(KMSServiceTest.KMSService.PagingEntity obj) {
            return base.Channel.GetGlobalNavigation(obj);
        }
        
        public System.Threading.Tasks.Task<KMSServiceTest.KMSService.JsonResult> GetGlobalNavigationAsync(KMSServiceTest.KMSService.PagingEntity obj) {
            return base.Channel.GetGlobalNavigationAsync(obj);
        }
        
        public KMSServiceTest.KMSService.JsonResult GetAnnouncementsItems(KMSServiceTest.KMSService.PagingEntity obj) {
            return base.Channel.GetAnnouncementsItems(obj);
        }
        
        public System.Threading.Tasks.Task<KMSServiceTest.KMSService.JsonResult> GetAnnouncementsItemsAsync(KMSServiceTest.KMSService.PagingEntity obj) {
            return base.Channel.GetAnnouncementsItemsAsync(obj);
        }
        
        public KMSServiceTest.KMSService.JsonResult GetSiteNavigation(KMSServiceTest.KMSService.PagingEntity obj) {
            return base.Channel.GetSiteNavigation(obj);
        }
        
        public System.Threading.Tasks.Task<KMSServiceTest.KMSService.JsonResult> GetSiteNavigationAsync(KMSServiceTest.KMSService.PagingEntity obj) {
            return base.Channel.GetSiteNavigationAsync(obj);
        }
    }
}
