//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envision.KMS.solution.Layouts.Envision.KMS.Solution.Handler {
    
    
    public partial class UserImageDelegate {
    }
}
