//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS_Copy.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KMS_Copy_Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KMS_Copy_Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KMS_Copy.Model.Resources.KMS_Copy.Global", typeof(KMS_Copy_Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMS Group.
        /// </summary>
        internal static string Definition_Group {
            get {
                return ResourceManager.GetString("Definition_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 答复.
        /// </summary>
        internal static string Field_Case_Comments {
            get {
                return ResourceManager.GetString("Field_Case_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        internal static string Field_Case_Content {
            get {
                return ResourceManager.GetString("Field_Case_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英文标题.
        /// </summary>
        internal static string Field_Case_EnglishTitle {
            get {
                return ResourceManager.GetString("Field_Case_EnglishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        internal static string Field_Case_Status {
            get {
                return ResourceManager.GetString("Field_Case_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类别.
        /// </summary>
        internal static string Field_Case_Type {
            get {
                return ResourceManager.GetString("Field_Case_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 负责人.
        /// </summary>
        internal static string Field_Case_User {
            get {
                return ResourceManager.GetString("Field_Case_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正文.
        /// </summary>
        internal static string Field_Email_Content {
            get {
                return ResourceManager.GetString("Field_Email_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        internal static string Field_Email_Subject {
            get {
                return ResourceManager.GetString("Field_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员联系方式.
        /// </summary>
        internal static string Field_KMS_AdminContact {
            get {
                return ResourceManager.GetString("Field_KMS_AdminContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩展字段1.
        /// </summary>
        internal static string Field_KMS_AdminField1 {
            get {
                return ResourceManager.GetString("Field_KMS_AdminField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩展字段2.
        /// </summary>
        internal static string Field_KMS_AdminField2 {
            get {
                return ResourceManager.GetString("Field_KMS_AdminField2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩展字段3.
        /// </summary>
        internal static string Field_KMS_AdminField3 {
            get {
                return ResourceManager.GetString("Field_KMS_AdminField3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员姓名.
        /// </summary>
        internal static string Field_KMS_AdminName {
            get {
                return ResourceManager.GetString("Field_KMS_AdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文名.
        /// </summary>
        internal static string Field_KMS_ChineseName {
            get {
                return ResourceManager.GetString("Field_KMS_ChineseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论数.
        /// </summary>
        internal static string Field_KMS_CommentsCount {
            get {
                return ResourceManager.GetString("Field_KMS_CommentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认值.
        /// </summary>
        internal static string Field_KMS_DefaultValue {
            get {
                return ResourceManager.GetString("Field_KMS_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        internal static string Field_KMS_Description {
            get {
                return ResourceManager.GetString("Field_KMS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英文内容.
        /// </summary>
        internal static string Field_KMS_EnglishHtmlContent {
            get {
                return ResourceManager.GetString("Field_KMS_EnglishHtmlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英文链接地址.
        /// </summary>
        internal static string Field_KMS_EnglishLink {
            get {
                return ResourceManager.GetString("Field_KMS_EnglishLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英文名.
        /// </summary>
        internal static string Field_KMS_EnglishName {
            get {
                return ResourceManager.GetString("Field_KMS_EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英文标题.
        /// </summary>
        internal static string Field_KMS_EnglishTitle {
            get {
                return ResourceManager.GetString("Field_KMS_EnglishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 论坛内容.
        /// </summary>
        internal static string Field_KMS_ForumContent {
            get {
                return ResourceManager.GetString("Field_KMS_ForumContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 论坛分类.
        /// </summary>
        internal static string Field_KMS_ForumType {
            get {
                return ResourceManager.GetString("Field_KMS_ForumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        internal static string Field_KMS_GlobalDesc {
            get {
                return ResourceManager.GetString("Field_KMS_GlobalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英文描述.
        /// </summary>
        internal static string Field_KMS_GlobalEngDesc {
            get {
                return ResourceManager.GetString("Field_KMS_GlobalEngDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滚动图片.
        /// </summary>
        internal static string Field_KMS_GlobalImg {
            get {
                return ResourceManager.GetString("Field_KMS_GlobalImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接地址.
        /// </summary>
        internal static string Field_KMS_GlobalLink {
            get {
                return ResourceManager.GetString("Field_KMS_GlobalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        internal static string Field_KMS_HtmlContent {
            get {
                return ResourceManager.GetString("Field_KMS_HtmlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否置顶.
        /// </summary>
        internal static string Field_KMS_IsTop {
            get {
                return ResourceManager.GetString("Field_KMS_IsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 词条分类.
        /// </summary>
        internal static string Field_KMS_Knowledge {
            get {
                return ResourceManager.GetString("Field_KMS_Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最后评论时间.
        /// </summary>
        internal static string Field_KMS_LastComments {
            get {
                return ResourceManager.GetString("Field_KMS_LastComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接地址.
        /// </summary>
        internal static string Field_KMS_Link {
            get {
                return ResourceManager.GetString("Field_KMS_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块.
        /// </summary>
        internal static string Field_KMS_Model {
            get {
                return ResourceManager.GetString("Field_KMS_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        internal static string Field_KMS_MultiContent {
            get {
                return ResourceManager.GetString("Field_KMS_MultiContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英文内容.
        /// </summary>
        internal static string Field_KMS_MultiEnglishContent {
            get {
                return ResourceManager.GetString("Field_KMS_MultiEnglishContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序.
        /// </summary>
        internal static string Field_KMS_Order {
            get {
                return ResourceManager.GetString("Field_KMS_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父级编号.
        /// </summary>
        internal static string Field_KMS_ParentNo {
            get {
                return ResourceManager.GetString("Field_KMS_ParentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关联导航.
        /// </summary>
        internal static string Field_KMS_RelatedGlobal {
            get {
                return ResourceManager.GetString("Field_KMS_RelatedGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编号.
        /// </summary>
        internal static string Field_KMS_SeriesNo {
            get {
                return ResourceManager.GetString("Field_KMS_SeriesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        internal static string Field_KMS_Status {
            get {
                return ResourceManager.GetString("Field_KMS_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看数.
        /// </summary>
        internal static string Field_KMS_ViewCount {
            get {
                return ResourceManager.GetString("Field_KMS_ViewCount", resourceCulture);
            }
        }
    }
}
